
// performance
export const FETCH_PERFORMANCE_LIST='FETCH_PERFORMANCE_LIST'
export const FETCH_PERFORMANCE = 'FETCH_PERFORMANCE'
export const FETCH_NOTICE_LIST = 'FETCH_NOTICE_LIST'
export const FETCH_NOTICE = 'FETCH_NOTICE'

// event
export const FETCH_EVENT_LIST = 'FETCH_EVENT_LIST'
export const FETCH_EVENT = 'FETCH_EVENT'