
export const FETCH_HALL = 'FETCH_HALL'
export const FETCH_HALL_LIST = 'FETCH_HALL_LIST'
export const FETCH_COUPON_LIST = 'FETCH_COUPON_LIST'
export const FETCH_COUPON = 'FETCH_COUPON'
// performance
export const FETCH_PERFORMANCE_LIST='FETCH_PERFORMANCE_LIST'
export const FETCH_PERFORMANCE = 'FETCH_PERFORMANCE'
export const FETCH_CONCERT_LIST = 'FETCH_CONCERT_LIST'
export const FETCH_MUSICAL_LIST = 'FETCH_MUSICAL_LIST'
export const FETCH_THEATER_LIST = 'FETCH_THEATER_LIST'
export const FETCH_EXHIBITION_LIST = 'FETCH_EXHIBITION_LIST'
export const FETCH_PERFORMANCE_EVENT = 'FETCH_PERFORMANCE_EVENT'

export const FETCH_REVIEW_LIST = 'FETCH_REVIEW_LIST'


export const FETCH_NOTICE_LIST = 'FETCH_NOTICE_LIST'
export const FETCH_NOTICE = 'FETCH_NOTICE'


export const FETCH_QNA_LIST = 'FETCH_QNA_LIST'
export const FETCH_QNA = 'FETCH_QNA'
export const FETCH_MEMBER_ROLE = 'FETCH_MEMBER_ROLE'
export const FETCH_QNA_COMMENT_LIST = 'FETCH_QNA_COMMENT_LIST'
export const FETCH_QNA_BEST_LIST = 'FETCH_QNA_BEST_LIST'
export const FETCH_QNA_BEST = 'FETCH_QNA_BEST'


export const FETCH_MEMBER_INFO = 'FETCH_MEMBER_INFO'
export const FETCH_MEMBER = 'FETCH_MEMBER'
export const FETCH_SEARCH_LIST = 'FETCH_SEARCH_LIST'
export const FETCH_SEARCH_LIST2 = 'FETCH_SEARCH_LIST2'
export const FETCH_NOTICE_SEARCH_LIST = 'FETCH_NOTICE_SEARCH_LIST'
export const FETCH_PERFORMANCE_LIKE = 'FETCH_PERFORMANCE_LIKE'
export const FETCH_MY_LIKE = 'FETCH_MY_LIKE'
export const FETCH_MY_QNA = 'FETCH_MY_QNA'
export const FETCH_MY_REVIEW = 'FETCH_MY_REVIEW'
export const FETCH_MY_TICKET = 'FETCH_MY_TICKET'

export const FETCH_EVENT_LIST = 'FETCH_EVENT_LIST'
export const FETCH_EVENT = 'FETCH_EVENT'

export const FETCH_EXPECT_LIST = 'FETCH_EXPECT_LIST'
export const FETCH_EXPECT = 'FETCH_EXPECT'

