
export const FETCH_HALL_LIST ='FETCH_HALL_LIST'
export const FETCH_HALL ='FETCH_HALL'
export const FETCH_COUPON_LIST = 'FETCH_COUPON_LIST'
export const FETCH_COUPON = 'FETCH_COUPON'

// performance
export const FETCH_PERFORMANCE_LIST='FETCH_PERFORMANCE_LIST'
export const FETCH_PERFORMANCE = 'FETCH_PERFORMANCE'
export const FETCH_NOTICE_LIST = 'FETCH_NOTICE_LIST'
export const FETCH_NOTICE = 'FETCH_NOTICE'


export const FETCH_QNA_LIST = 'FETCH_QNA_LIST'
export const FETCH_QNA = 'FETCH_QNA'
export const FETCH_MEMBER_ROLE = 'FETCH_MEMBER_ROLE'
export const FETCH_QNA_COMMENT_LIST = 'FETCH_QNA_COMMENT_LIST'
export const FETCH_QNA_BEST_LIST = 'FETCH_QNA_BEST_LIST'
export const FETCH_QNA_BEST = 'FETCH_QNA_BEST'


export const FETCH_MEMBER_INFO = 'FETCH_MEMBER_INFO'
export const FETCH_MEMBER = 'FETCH_MEMBER'
